/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AppQuery.graphql
 * @generated SignedSource<<06e8ec6888529362f75760a8e3c91c20>>
 * @relayHash ee041eceb578c8e665ddf518bd7ff33d
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query AppQuery {
  partners {
    ...partnerList
    ...partnerDetail
  }
}

fragment partnerList on Partner {
  partnerNumber
  firstname
  ...partnerListEntry
}

fragment partnerDetail on Partner {
  partnerNumber
  firstname
  lastname
  birthday
}

fragment partnerListEntry on Partner {
  partnerNumber
  firstname
  lastname
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "AppQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Partner",
        "name": "partners",
        "plural": true,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "partnerList",
            "args": null
          },
          {
            "kind": "FragmentSpread",
            "name": "partnerDetail",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "AppQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "AppQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Partner",
        "name": "partners",
        "plural": true,
        "selections": [
          {
            "kind": "InlineFragment",
            "type": "Partner",
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "partnerNumber",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "firstname",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "lastname",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "birthday",
                "storageKey": null
              }
            ]
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query AppQuery {\n  partners {\n    ...partnerList\n    ...partnerDetail\n  }\n}\n\nfragment partnerList on Partner {\n  partnerNumber\n  firstname\n  ...partnerListEntry\n}\n\nfragment partnerDetail on Partner {\n  partnerNumber\n  firstname\n  lastname\n  birthday\n}\n\nfragment partnerListEntry on Partner {\n  partnerNumber\n  firstname\n  lastname\n}\n"
};

module.exports = batch;
