/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule partnerDetailQuery.graphql
 * @generated SignedSource<<94de0613467f6b29d391285f7b6d3027>>
 * @relayHash 8616a31555c1a4a146014598205c8e73
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query partnerDetailQuery(
  $partnerNumber: Int!
) {
  partner(partnerNumber: $partnerNumber) {
    partnerNumber
    firstname
    lastname
    birthday
    sex
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "partnerNumber",
        "type": "Int!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "partnerDetailQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "partnerNumber",
            "variableName": "partnerNumber",
            "type": "Int!"
          }
        ],
        "concreteType": "Partner",
        "name": "partner",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "partnerNumber",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "firstname",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "lastname",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "birthday",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "sex",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "partnerDetailQuery",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "partnerNumber",
        "type": "Int!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "partnerDetailQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "partnerNumber",
            "variableName": "partnerNumber",
            "type": "Int!"
          }
        ],
        "concreteType": "Partner",
        "name": "partner",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "partnerNumber",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "firstname",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "lastname",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "birthday",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "sex",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query partnerDetailQuery(\n  $partnerNumber: Int!\n) {\n  partner(partnerNumber: $partnerNumber) {\n    partnerNumber\n    firstname\n    lastname\n    birthday\n    sex\n  }\n}\n"
};

module.exports = batch;
