/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule partnerListQuery.graphql
 * @generated SignedSource<<eb2322d4b91f75ed8ca0ce4bba29ff6c>>
 * @relayHash 4d22f9b68cfe97a806cf35ada49337f9
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query partnerListQuery {
  partners {
    partnerNumber
    ...partnerListEntry
  }
}

fragment partnerListEntry on Partner {
  partnerNumber
  firstname
  lastname
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "partnerListQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Partner",
        "name": "partners",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "partnerNumber",
            "storageKey": null
          },
          {
            "kind": "FragmentSpread",
            "name": "partnerListEntry",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "partnerListQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "partnerListQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Partner",
        "name": "partners",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "partnerNumber",
            "storageKey": null
          },
          {
            "kind": "InlineFragment",
            "type": "Partner",
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "firstname",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "lastname",
                "storageKey": null
              }
            ]
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query partnerListQuery {\n  partners {\n    partnerNumber\n    ...partnerListEntry\n  }\n}\n\nfragment partnerListEntry on Partner {\n  partnerNumber\n  firstname\n  lastname\n}\n"
};

module.exports = batch;
