/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule partnerDetailMyClaimsListEntry.graphql
 * @generated SignedSource<<c103d189a68dcaa18a5f484b50f8eba3>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type partnerDetailMyClaimsListEntry = {|
  +claimsNumber: ?number;
  +description: ?string;
  +claimsSum: number;
  +claimsDate: string;
  +state: "clearing" | "closed" | "reported";
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "partnerDetailMyClaimsListEntry",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "claimsNumber",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "description",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "claimsSum",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "claimsDate",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "state",
      "storageKey": null
    }
  ],
  "type": "Claims"
};

module.exports = fragment;
