/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule partnerListEntry.graphql
 * @generated SignedSource<<01c508c0cb68c8c34a1892691f31af09>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type partnerListEntry = {
  partnerNumber?: ?number;
  firstname: string;
  lastname: string;
  myClaims?: ?Array<?partnerListEntry_myClaims>;
};

export type partnerListEntry_myClaims = {
  claimsSum: number;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "partnerListEntry",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "partnerNumber",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "firstname",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "lastname",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Claims",
      "name": "myClaims",
      "plural": true,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "claimsSum",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Partner"
};

module.exports = fragment;
