/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule partnerDetailMyClaimsList.graphql
 * @generated SignedSource<<1e089e01b57df16103c761d62d070bb1>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type partnerDetailMyClaimsList = {|
  +claimsNumber: ?number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "plural": true
  },
  "name": "partnerDetailMyClaimsList",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "claimsNumber",
      "storageKey": null
    },
    {
      "kind": "FragmentSpread",
      "name": "partnerDetailMyClaimsListEntry",
      "args": null
    }
  ],
  "type": "Claims"
};

module.exports = fragment;
