/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule partnerListQuery.graphql
 * @generated SignedSource<<5e299a16029b843db92fe5a9f7f24706>>
 * @relayHash 65457cb44cec31dabc28adc70ec84f34
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query partnerListQuery {
  partners {
    partnerNumber
    ...partnerListEntry
  }
}

fragment partnerListEntry on Partner {
  partnerNumber
  firstname
  lastname
  myClaims {
    claimsSum
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "partnerListQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Partner",
        "name": "partners",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "partnerNumber",
            "storageKey": null
          },
          {
            "kind": "FragmentSpread",
            "name": "partnerListEntry",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "partnerListQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "partnerListQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Partner",
        "name": "partners",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "partnerNumber",
            "storageKey": null
          },
          {
            "kind": "InlineFragment",
            "type": "Partner",
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "firstname",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "lastname",
                "storageKey": null
              },
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "Claims",
                "name": "myClaims",
                "plural": true,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "claimsSum",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ]
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query partnerListQuery {\n  partners {\n    partnerNumber\n    ...partnerListEntry\n  }\n}\n\nfragment partnerListEntry on Partner {\n  partnerNumber\n  firstname\n  lastname\n  myClaims {\n    claimsSum\n  }\n}\n"
};

module.exports = batch;
