/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule partnerDetailMyClaimsList.graphql
 * @generated SignedSource<<ada2975b57ea937ef3467827420c34ab>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type partnerDetailMyClaimsList = {|
  +partnerNumber: ?number;
  +myClaims: ?$ReadOnlyArray<?{|
    +claimsNumber: ?number;
  |}>;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "partnerDetailMyClaimsList",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "partnerNumber",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Claims",
      "name": "myClaims",
      "plural": true,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "claimsNumber",
          "storageKey": null
        },
        {
          "kind": "FragmentSpread",
          "name": "partnerDetailMyClaimsListEntry",
          "args": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Partner"
};

module.exports = fragment;
