/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule partnerList.graphql
 * @generated SignedSource<<5f7b796ae4da640ba868bd539f824b7a>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type partnerList = {
  partnerNumber: string;
  firstname: string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "plural": true
  },
  "name": "partnerList",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "partnerNumber",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "firstname",
      "storageKey": null
    },
    {
      "kind": "FragmentSpread",
      "name": "partnerListEntry",
      "args": null
    }
  ],
  "type": "Partner"
};

module.exports = fragment;
