/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule partnerDetail.graphql
 * @generated SignedSource<<a573faffe680610a5ef3082cc5f33ffa>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type partnerDetail = {
  partnerNumber: string;
  firstname: string;
  lastname: string;
  birthday: string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "partnerDetail",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "partnerNumber",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "firstname",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "lastname",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "birthday",
      "storageKey": null
    }
  ],
  "type": "Partner"
};

module.exports = fragment;
