/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule partnerListEntry.graphql
 * @generated SignedSource<<de4c79f6f2d682bc5d71807c8c3f341c>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type partnerListEntry = {|
  +partnerNumber: ?number;
  +firstname: string;
  +lastname: string;
  +birthday: string;
  +myClaims: ?$ReadOnlyArray<?{|
    +claimsSum: number;
  |}>;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "partnerListEntry",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "partnerNumber",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "firstname",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "lastname",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "birthday",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Claims",
      "name": "myClaims",
      "plural": true,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "claimsSum",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Partner"
};

module.exports = fragment;
